# Generated by Django 5.1.3 on 2025-07-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='교회 이름')),
                ('timezone', models.CharField(default='Asia/Seoul', max_length=50, verbose_name='시간대')),
                ('domain', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='교회 도메인')),
                ('settings', models.JSONField(default=dict, verbose_name='교회별 커스텀 설정')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
