# Generated by Django 5.2.1 on 2025-07-10 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PRAYER', '기도'), ('NEWS', '생활소식'), ('HOSPITAL_VISIT', '병문안'), ('ETC', '기타')], max_length=20, verbose_name='기록 유형')),
                ('content', models.TextField(verbose_name='내용')),
                ('date', models.DateField(verbose_name='기록일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.church', verbose_name='소속 교회')),
            ],
            options={
                'verbose_name': '생활소식/심방기록',
                'verbose_name_plural': '생활소식/심방기록',
                'ordering': ['-date'],
            },
        ),
    ]
