# Generated by Django 5.2.1 on 2025-07-10 03:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('is_verified', models.BooleanField(default=False, verbose_name='이메일 인증 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자들',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChurchUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', '슈퍼 관리자'), ('church_admin', '교회 관리자'), ('church_staff', '교회 직원'), ('member', '일반 교인')], default='member', max_length=20, verbose_name='역할')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_users', to='church.church', verbose_name='교회')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_users', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '교회 사용자',
                'verbose_name_plural': '교회 사용자들',
                'db_table': 'church_users',
            },
        ),
        migrations.CreateModel(
            name='DetailedPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='권한 카테고리')),
                ('action', models.CharField(choices=[('view', '조회'), ('create', '생성'), ('update', '수정'), ('delete', '삭제')], default='view', max_length=20, verbose_name='액션')),
                ('scope', models.CharField(choices=[('own', '본인 데이터만'), ('own_group', '본인 그룹 데이터'), ('all', '모든 데이터')], default='own', max_length=20, verbose_name='범위')),
                ('is_granted', models.BooleanField(default=True, verbose_name='권한 부여 여부')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='부여일')),
                ('church_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_permissions', to='users.churchuser', verbose_name='교회 사용자')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='부여자')),
            ],
            options={
                'verbose_name': '세부 권한',
                'verbose_name_plural': '세부 권한들',
                'db_table': 'detailed_permissions',
            },
        ),
        migrations.CreateModel(
            name='MinistryRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry_type', models.CharField(max_length=50, verbose_name='사역 유형')),
                ('permissions', models.JSONField(default=list, verbose_name='권한 목록')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='할당일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('church_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ministry_roles', to='users.churchuser', verbose_name='교회 사용자')),
            ],
            options={
                'verbose_name': '사역 역할',
                'verbose_name_plural': '사역 역할들',
                'db_table': 'ministry_roles',
            },
        ),
    ]
