# Generated by Django 5.2.1 on 2025-07-10 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('volunteering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministryrole',
            name='volunteer_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='volunteering.volunteerrole', verbose_name='봉사 역할'),
        ),
        migrations.AddIndex(
            model_name='churchuser',
            index=models.Index(fields=['church', 'role'], name='church_user_church__08358d_idx'),
        ),
        migrations.AddIndex(
            model_name='churchuser',
            index=models.Index(fields=['church', 'is_active'], name='church_user_church__066e34_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='churchuser',
            unique_together={('user', 'church')},
        ),
        migrations.AddIndex(
            model_name='detailedpermission',
            index=models.Index(fields=['church_user', 'category'], name='detailed_pe_church__465950_idx'),
        ),
        migrations.AddIndex(
            model_name='detailedpermission',
            index=models.Index(fields=['church_user', 'is_granted'], name='detailed_pe_church__d2241d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detailedpermission',
            unique_together={('church_user', 'category', 'action', 'scope')},
        ),
        migrations.AlterUniqueTogether(
            name='ministryrole',
            unique_together={('church_user', 'ministry_type')},
        ),
    ]
