# Generated by Django 5.1.3 on 2025-07-09 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='봉사 제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('date', models.DateField(verbose_name='봉사일')),
                ('target_roles', models.JSONField(blank=True, default=list, verbose_name='대상 직책 (JSON 배열)')),
                ('max_people', models.PositiveIntegerField(blank=True, null=True, verbose_name='최대 인원')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicants', models.ManyToManyField(blank=True, to='members.member', verbose_name='신청 교인')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.church', verbose_name='소속 교회')),
            ],
            options={
                'verbose_name': '봉사 신청',
                'verbose_name_plural': '봉사 신청',
                'ordering': ['-date'],
            },
        ),
    ]
