# Generated by Django 5.2.1 on 2025-07-10 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
        ('groups', '0001_initial'),
        ('members', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='역할명')),
                ('code', models.CharField(help_text='영문/숫자로 구성된 고유 코드 (예: children_teacher)', max_length=50, verbose_name='역할 코드')),
                ('description', models.TextField(blank=True, verbose_name='역할 설명')),
                ('category', models.CharField(choices=[('department', '부서 사역'), ('worship', '예배 사역'), ('education', '교육 사역'), ('care', '돌봄 사역'), ('outreach', '전도/선교 사역'), ('facility', '시설 관리'), ('media', '미디어/기술'), ('administration', '행정 업무'), ('special', '특별 사역'), ('other', '기타')], default='other', max_length=20, verbose_name='카테고리')),
                ('required_level', models.CharField(choices=[('anyone', '누구나'), ('member', '교인만'), ('experienced', '경험자'), ('trained', '훈련 이수자'), ('appointed', '임명된 자')], default='member', max_length=20, verbose_name='필요 자격')),
                ('requires_training', models.BooleanField(default=False, verbose_name='교육 필수')),
                ('training_requirements', models.TextField(blank=True, verbose_name='교육 요구사항')),
                ('default_permissions', models.JSONField(blank=True, default=list, help_text='이 역할에 자동으로 부여되는 권한 목록', verbose_name='기본 권한')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('max_assignees', models.PositiveIntegerField(blank=True, null=True, verbose_name='최대 임명 인원')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_roles', to='church.church', verbose_name='소속 교회')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_volunteer_roles', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('target_groups', models.ManyToManyField(blank=True, help_text='이 역할이 관리하는 그룹들', to='groups.group', verbose_name='담당 그룹')),
            ],
            options={
                'verbose_name': '봉사 역할',
                'verbose_name_plural': '봉사 역할들',
                'db_table': 'volunteer_roles',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, verbose_name='할당일')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('custom_permissions', models.JSONField(blank=True, default=list, help_text='기본 권한에 추가로 부여된 권한들', verbose_name='개별 권한')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인일')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_assignments', to=settings.AUTH_USER_MODEL, verbose_name='승인자')),
                ('church_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_assignments', to='users.churchuser', verbose_name='교회 사용자')),
                ('volunteer_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_assignments', to='volunteering.volunteerrole', verbose_name='봉사 역할')),
            ],
            options={
                'verbose_name': '봉사 할당',
                'verbose_name_plural': '봉사 할당들',
                'db_table': 'volunteer_assignments',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='봉사 제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('date', models.DateField(verbose_name='봉사일')),
                ('target_roles', models.JSONField(blank=True, default=list, verbose_name='대상 직책 (JSON 배열)')),
                ('max_people', models.PositiveIntegerField(blank=True, null=True, verbose_name='최대 인원')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicants', models.ManyToManyField(blank=True, to='members.member', verbose_name='신청 교인')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.church', verbose_name='소속 교회')),
                ('volunteer_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunteering.volunteerrole', verbose_name='관련 봉사 역할')),
            ],
            options={
                'verbose_name': '봉사 신청',
                'verbose_name_plural': '봉사 신청',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='volunteerrole',
            index=models.Index(fields=['church', 'category'], name='volunteer_r_church__590704_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteerrole',
            index=models.Index(fields=['church', 'is_active'], name='volunteer_r_church__86f042_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteerrole',
            index=models.Index(fields=['code'], name='volunteer_r_code_9459ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='volunteerrole',
            unique_together={('church', 'code')},
        ),
        migrations.AddIndex(
            model_name='volunteerassignment',
            index=models.Index(fields=['church_user', 'is_active'], name='volunteer_a_church__d3944d_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteerassignment',
            index=models.Index(fields=['volunteer_role', 'is_active'], name='volunteer_a_volunte_2b4c70_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='volunteerassignment',
            unique_together={('church_user', 'volunteer_role')},
        ),
    ]
