# Generated by Django 5.2.1 on 2025-07-10 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
        ('groups', '0002_initial'),
        ('reports', '0001_initial'),
        ('users', '0001_initial'),
        ('volunteering', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dashboards', to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AddField(
            model_name='exportlog',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_logs', to='church.church', verbose_name='교회'),
        ),
        migrations.AddField(
            model_name='exportlog',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_logs', to=settings.AUTH_USER_MODEL, verbose_name='요청자'),
        ),
        migrations.AddField(
            model_name='ministryreport',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ministry_reports', to='church.church', verbose_name='교회'),
        ),
        migrations.AddField(
            model_name='ministryreport',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministry_reports', to='groups.group', verbose_name='담당 부서/그룹'),
        ),
        migrations.AddField(
            model_name='ministryreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ministry_reports', to='users.churchuser', verbose_name='보고자'),
        ),
        migrations.AddField(
            model_name='ministryreport',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ministry_reports', to='users.churchuser', verbose_name='검토자'),
        ),
        migrations.AddField(
            model_name='ministryreport',
            name='volunteer_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministry_reports', to='volunteering.volunteerrole', verbose_name='봉사 역할'),
        ),
        migrations.AddField(
            model_name='ministryreportcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.churchuser', verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='ministryreportcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reports.ministryreportcomment', verbose_name='부모 댓글'),
        ),
        migrations.AddField(
            model_name='ministryreportcomment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.ministryreport', verbose_name='보고서'),
        ),
        migrations.AddField(
            model_name='ministryreporttemplate',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ministry_report_templates', to='church.church', verbose_name='교회'),
        ),
        migrations.AddField(
            model_name='ministryreporttemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ministry_report_templates', to='users.churchuser', verbose_name='생성자'),
        ),
        migrations.AddField(
            model_name='ministryreporttemplate',
            name='default_reviewers',
            field=models.ManyToManyField(blank=True, help_text='이 템플릿으로 작성된 보고서의 기본 검토자들', to='users.churchuser', verbose_name='기본 검토자'),
        ),
        migrations.AddField(
            model_name='ministryreporttemplate',
            name='target_groups',
            field=models.ManyToManyField(blank=True, help_text='이 템플릿을 사용할 그룹들', to='groups.group', verbose_name='적용 그룹'),
        ),
        migrations.AddField(
            model_name='ministryreporttemplate',
            name='target_roles',
            field=models.ManyToManyField(blank=True, help_text='이 템플릿을 사용할 봉사 역할들', to='volunteering.volunteerrole', verbose_name='적용 봉사 역할'),
        ),
        migrations.AddField(
            model_name='report',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='church.church', verbose_name='교회'),
        ),
        migrations.AddField(
            model_name='report',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='church.church', verbose_name='교회'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_templates', to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.reporttemplate', verbose_name='템플릿'),
        ),
        migrations.AddField(
            model_name='report',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='reports.reporttemplate', verbose_name='템플릿'),
        ),
        migrations.AddField(
            model_name='statisticssummary',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics_summaries', to='church.church', verbose_name='교회'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboard',
            unique_together={('church', 'name')},
        ),
        migrations.AddIndex(
            model_name='exportlog',
            index=models.Index(fields=['church', 'status'], name='export_logs_church__1b20cf_idx'),
        ),
        migrations.AddIndex(
            model_name='exportlog',
            index=models.Index(fields=['requested_by', 'status'], name='export_logs_request_52c9f2_idx'),
        ),
        migrations.AddIndex(
            model_name='ministryreport',
            index=models.Index(fields=['church', 'status'], name='ministry_re_church__201b3b_idx'),
        ),
        migrations.AddIndex(
            model_name='ministryreport',
            index=models.Index(fields=['reporter', 'status'], name='ministry_re_reporte_355b3b_idx'),
        ),
        migrations.AddIndex(
            model_name='ministryreport',
            index=models.Index(fields=['department', 'report_date'], name='ministry_re_departm_d93e41_idx'),
        ),
        migrations.AddIndex(
            model_name='ministryreport',
            index=models.Index(fields=['category', 'report_date'], name='ministry_re_categor_e89dd5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ministryreporttemplate',
            unique_together={('church', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='reporttemplate',
            unique_together={('church', 'name')},
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['church', 'status'], name='reports_church__144e80_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['template', 'start_date'], name='reports_templat_11e313_idx'),
        ),
        migrations.AddIndex(
            model_name='statisticssummary',
            index=models.Index(fields=['church', 'date'], name='statistics__church__9b9261_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='statisticssummary',
            unique_together={('church', 'date')},
        ),
    ]
