# Generated by Django 5.2.1 on 2025-07-10 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', '신청'), ('ATTENDED', '출석'), ('COMPLETED', '수료'), ('CANCELED', '취소')], default='APPLIED', max_length=10, verbose_name='상태')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='신청일')),
            ],
            options={
                'verbose_name': '교육 신청',
                'verbose_name_plural': '교육 신청',
            },
        ),
        migrations.CreateModel(
            name='EducationProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='프로그램 제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('date', models.DateField(verbose_name='교육일')),
                ('registration_deadline', models.DateField(verbose_name='등록 마감일')),
                ('target_roles', models.JSONField(blank=True, default=list, verbose_name='대상 직책 (JSON 배열)')),
                ('max_people', models.PositiveIntegerField(blank=True, null=True, verbose_name='최대 인원')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.church', verbose_name='소속 교회')),
            ],
            options={
                'verbose_name': '교육 프로그램',
                'verbose_name_plural': '교육 프로그램',
                'ordering': ['-date'],
            },
        ),
    ]
