# Generated by Django 5.2.1 on 2025-07-10 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationregistration',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='신청 교인'),
        ),
        migrations.AddField(
            model_name='educationregistration',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.educationprogram', verbose_name='교육 프로그램'),
        ),
        migrations.AlterUniqueTogether(
            name='educationregistration',
            unique_together={('program', 'member')},
        ),
    ]
