# Generated by Django 5.2.1 on 2025-07-10 03:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JWTBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_jti', models.CharField(max_length=255, unique=True, verbose_name='JWT ID')),
                ('blacklisted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='블랙리스트 등록일')),
                ('reason', models.CharField(choices=[('logout', '로그아웃'), ('security', '보안상 이유'), ('expired', '만료'), ('revoked', '관리자 취소')], max_length=100, verbose_name='블랙리스트 사유')),
                ('expires_at', models.DateTimeField(verbose_name='토큰 만료일')),
            ],
            options={
                'verbose_name': 'JWT 블랙리스트',
                'verbose_name_plural': 'JWT 블랙리스트들',
                'db_table': 'jwt_blacklist',
            },
        ),
        migrations.CreateModel(
            name='UserSecurityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, verbose_name='로그인 실패 횟수')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='계정 잠금 해제 시간')),
                ('last_failed_login', models.DateTimeField(blank=True, null=True, verbose_name='마지막 로그인 실패 시간')),
                ('password_changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='비밀번호 변경일')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='마지막 로그인 IP')),
            ],
            options={
                'verbose_name': '사용자 보안 프로필',
                'verbose_name_plural': '사용자 보안 프로필들',
                'db_table': 'user_security_profiles',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='액션')),
                ('resource', models.CharField(max_length=100, verbose_name='리소스')),
                ('resource_id', models.CharField(blank=True, max_length=50, verbose_name='리소스 ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 주소')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일')),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.church', verbose_name='교회')),
            ],
            options={
                'verbose_name': '활동 로그',
                'verbose_name_plural': '활동 로그들',
                'db_table': 'activity_logs',
            },
        ),
    ]
