# Generated by Django 5.2.1 on 2025-07-10 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='jwtblacklist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='usersecurityprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'created_at'], name='activity_lo_user_id_d23b30_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['church', 'created_at'], name='activity_lo_church__d0645d_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action', 'created_at'], name='activity_lo_action_0f3584_idx'),
        ),
        migrations.AddIndex(
            model_name='jwtblacklist',
            index=models.Index(fields=['token_jti'], name='jwt_blackli_token_j_6cb209_idx'),
        ),
        migrations.AddIndex(
            model_name='jwtblacklist',
            index=models.Index(fields=['user', 'blacklisted_at'], name='jwt_blackli_user_id_3d5215_idx'),
        ),
    ]
