# Generated by Django 5.2.1 on 2025-07-10 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorshipRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='예배일')),
                ('worship_type', models.CharField(choices=[('SUNDAY', '주일예배'), ('WEDNESDAY', '수요예배'), ('FRIDAY', '금요철야'), ('DAWN', '새벽예배'), ('SPECIAL', '특별집회'), ('ETC', '기타')], max_length=20, verbose_name='예배 종류')),
                ('preacher', models.CharField(max_length=100, verbose_name='설교자')),
                ('theme', models.CharField(blank=True, max_length=200, verbose_name='설교 주제')),
                ('scripture', models.CharField(blank=True, max_length=200, verbose_name='성경 구절')),
                ('summary', models.TextField(blank=True, verbose_name='요약')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, to='members.member', verbose_name='참석 교인')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.church', verbose_name='소속 교회')),
            ],
            options={
                'verbose_name': '예배 기록',
                'verbose_name_plural': '예배 기록',
                'ordering': ['-date'],
            },
        ),
    ]
