# Generated by Django 5.1.3 on 2025-07-09 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('file', models.FileField(upload_to='bulletins/', verbose_name='주보 파일 (PDF)')),
                ('date', models.DateField(verbose_name='발행일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.church', verbose_name='소속 교회')),
            ],
            options={
                'verbose_name': '주보',
                'verbose_name_plural': '주보',
                'ordering': ['-date'],
            },
        ),
    ]
