# Generated by Django 5.2.1 on 2025-07-10 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='질문 내용')),
                ('question_type', models.CharField(choices=[('TEXT', '주관식'), ('SINGLE_CHOICE', '단일 선택'), ('MULTIPLE_CHOICE', '다중 선택')], max_length=20, verbose_name='질문 유형')),
                ('choices', models.JSONField(blank=True, default=list, verbose_name='선택지 (JSON 배열)')),
            ],
            options={
                'verbose_name': '질문',
                'verbose_name_plural': '질문',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, verbose_name='주관식 응답')),
                ('selected_choices', models.JSONField(blank=True, default=list, verbose_name='선택된 선택지 (JSON 배열)')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='응답 시각')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='응답 교인')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.question', verbose_name='질문')),
            ],
            options={
                'verbose_name': '응답',
                'verbose_name_plural': '응답',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='설문 제목')),
                ('description', models.TextField(blank=True, verbose_name='설문 설명')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.church', verbose_name='소속 교회')),
            ],
            options={
                'verbose_name': '설문조사',
                'verbose_name_plural': '설문조사',
                'ordering': ['-created_at'],
            },
        ),
    ]
