# Generated by Django 5.2.1 on 2025-07-10 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='금액')),
                ('offering_type', models.CharField(choices=[('TITHE', '십일조'), ('THANKSGIVING', '감사헌금'), ('MISSION', '선교헌금'), ('BUILDING', '건축헌금'), ('ETC', '기타헌금')], max_length=20, verbose_name='헌금 종류')),
                ('date', models.DateField(verbose_name='헌금일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.church', verbose_name='소속 교회')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member', verbose_name='교인 (익명 가능)')),
            ],
            options={
                'verbose_name': '헌금 기록',
                'verbose_name_plural': '헌금 기록',
                'ordering': ['-date'],
            },
        ),
    ]
