# Generated by Django 5.2.1 on 2025-07-10 03:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('is_encouragement', models.BooleanField(default=False, verbose_name='격려 댓글')),
                ('is_private', models.BooleanField(default=False, verbose_name='비공개 댓글')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '기도제목 댓글',
                'verbose_name_plural': '기도제목 댓글들',
                'db_table': 'prayer_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrayerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='그룹명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_public', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('meeting_day', models.CharField(blank=True, max_length=20, verbose_name='정기 모임 요일')),
                ('meeting_time', models.TimeField(blank=True, null=True, verbose_name='모임 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '기도 그룹',
                'verbose_name_plural': '기도 그룹들',
                'db_table': 'prayer_groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrayerGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', '리더'), ('member', '멤버')], default='member', max_length=20, verbose_name='역할')),
                ('joined_date', models.DateField(default=django.utils.timezone.now, verbose_name='가입일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
            ],
            options={
                'verbose_name': '기도 그룹 멤버',
                'verbose_name_plural': '기도 그룹 멤버들',
                'db_table': 'prayer_group_members',
            },
        ),
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='기도제목 내용')),
                ('prayer_type', models.CharField(choices=[('personal', '개인'), ('family', '가정'), ('church', '교회'), ('mission', '선교'), ('healing', '치유'), ('thanksgiving', '감사'), ('guidance', '인도'), ('other', '기타')], default='personal', max_length=20, verbose_name='기도제목 유형')),
                ('priority', models.CharField(choices=[('low', '낮음'), ('medium', '보통'), ('high', '높음'), ('urgent', '긴급')], default='medium', max_length=20, verbose_name='우선순위')),
                ('status', models.CharField(choices=[('active', '진행중'), ('answered', '응답됨'), ('closed', '종료됨'), ('private', '비공개')], default='active', max_length=20, verbose_name='상태')),
                ('is_public', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('is_shared_with_leaders', models.BooleanField(default=False, verbose_name='리더진 공유')),
                ('prayer_date', models.DateField(default=django.utils.timezone.now, verbose_name='기도 시작일')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='목표 날짜')),
                ('answered_date', models.DateField(blank=True, null=True, verbose_name='응답 날짜')),
                ('tags', models.CharField(blank=True, help_text='쉼표로 구분하여 입력', max_length=200, verbose_name='태그')),
                ('answer_note', models.TextField(blank=True, verbose_name='응답 메모')),
                ('private_note', models.TextField(blank=True, verbose_name='비공개 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('prayer_count', models.IntegerField(default=0, verbose_name='기도 카운트')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayers', to='church.church', verbose_name='소속 교회')),
            ],
            options={
                'verbose_name': '기도제목',
                'verbose_name_plural': '기도제목들',
                'db_table': 'prayers',
                'ordering': ['-created_at'],
            },
        ),
    ]
