# Generated by Django 5.2.1 on 2025-07-10 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
        ('groups', '0002_initial'),
        ('members', '0002_initial'),
        ('prayers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prayer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prayers', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='prayer',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prayers', to='groups.group', verbose_name='그룹'),
        ),
        migrations.AddField(
            model_name='prayer',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayers', to='members.member', verbose_name='교인'),
        ),
        migrations.AddField(
            model_name='prayercomment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_comments', to='members.member', verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='prayercomment',
            name='prayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='prayers.prayer', verbose_name='기도제목'),
        ),
        migrations.AddField(
            model_name='prayergroup',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_groups', to='church.church', verbose_name='소속 교회'),
        ),
        migrations.AddField(
            model_name='prayergroup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prayer_groups', to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AddField(
            model_name='prayergroupmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_group_memberships', to='members.member', verbose_name='멤버'),
        ),
        migrations.AddField(
            model_name='prayergroupmember',
            name='prayer_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='prayers.prayergroup', verbose_name='기도 그룹'),
        ),
        migrations.AddField(
            model_name='prayergroup',
            name='members',
            field=models.ManyToManyField(related_name='prayer_groups', through='prayers.PrayerGroupMember', to='members.member', verbose_name='멤버들'),
        ),
        migrations.AddIndex(
            model_name='prayer',
            index=models.Index(fields=['church', 'status'], name='prayers_church__d87c18_idx'),
        ),
        migrations.AddIndex(
            model_name='prayer',
            index=models.Index(fields=['member', 'prayer_date'], name='prayers_member__718025_idx'),
        ),
        migrations.AddIndex(
            model_name='prayer',
            index=models.Index(fields=['prayer_type', 'priority'], name='prayers_prayer__8e45c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prayergroupmember',
            unique_together={('prayer_group', 'member')},
        ),
    ]
