# Generated by Django 5.1.3 on 2025-07-09 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='그룹 이름')),
                ('group_type', models.CharField(choices=[('DEPARTMENT', '부서'), ('DISTRICT', '구역'), ('CHOIR', '찬양대'), ('ETC', '기타')], max_length=20, verbose_name='그룹 종류')),
                ('management_type', models.CharField(choices=[('AUTO', '자동'), ('MANUAL', '수동')], default='MANUAL', max_length=10, verbose_name='관리 유형')),
                ('age_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='최소 연령')),
                ('age_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='최대 연령')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.church', verbose_name='소속 교회')),
            ],
        ),
    ]
