# Generated by Django 5.2.1 on 2025-07-10 03:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', '그룹장'), ('sub_leader', '부그룹장'), ('member', '그룹원'), ('secretary', '총무')], default='member', max_length=20, verbose_name='역할')),
                ('joined_date', models.DateField(default=django.utils.timezone.now, verbose_name='가입일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
            ],
            options={
                'verbose_name': '그룹 멤버',
                'verbose_name_plural': '그룹 멤버들',
                'db_table': 'group_members',
                'ordering': ['-role', 'member__name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='그룹명')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='그룹 코드')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('group_type', models.CharField(choices=[('department', '부서'), ('district', '구역'), ('cell', '셀/소그룹'), ('choir', '찬양대'), ('committee', '위원회'), ('ministry', '사역팀'), ('other', '기타')], default='department', max_length=20, verbose_name='그룹 종류')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('management_type', models.CharField(choices=[('auto', '자동 (나이 기준)'), ('manual', '수동'), ('hybrid', '혼합 (자동+수동)')], default='manual', max_length=10, verbose_name='관리 유형')),
                ('age_min', models.PositiveIntegerField(blank=True, help_text='자동 관리 시 최소 나이', null=True, verbose_name='최소 연령')),
                ('age_max', models.PositiveIntegerField(blank=True, help_text='자동 관리 시 최대 나이', null=True, verbose_name='최대 연령')),
                ('meeting_day', models.CharField(blank=True, help_text='예: 주일, 수요일, 매주 금요일', max_length=20, verbose_name='정기 모임 요일')),
                ('meeting_time', models.TimeField(blank=True, null=True, verbose_name='모임 시간')),
                ('meeting_place', models.CharField(blank=True, max_length=100, verbose_name='모임 장소')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('max_members', models.IntegerField(blank=True, help_text='그룹 최대 인원 제한', null=True, verbose_name='최대 인원')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='church.church', verbose_name='소속 교회')),
            ],
            options={
                'verbose_name': '그룹',
                'verbose_name_plural': '그룹들',
                'db_table': 'groups',
                'ordering': ['order', 'name'],
            },
        ),
    ]
