# Generated by Django 5.2.1 on 2025-07-10 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='책명')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='책 코드')),
                ('testament', models.CharField(choices=[('old', '구약'), ('new', '신약')], max_length=10, verbose_name='구분')),
                ('order', models.IntegerField(verbose_name='순서')),
                ('chapter_count', models.IntegerField(verbose_name='장 수')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '성경 책',
                'verbose_name_plural': '성경 책들',
                'db_table': 'bible_books',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BibleStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('start_chapter', models.IntegerField(verbose_name='시작 장')),
                ('start_verse', models.IntegerField(verbose_name='시작 절')),
                ('end_chapter', models.IntegerField(verbose_name='마지막 장')),
                ('end_verse', models.IntegerField(verbose_name='마지막 절')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '성경 공부',
                'verbose_name_plural': '성경 공부들',
                'db_table': 'bible_studies',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BibleVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField(verbose_name='장')),
                ('verse', models.IntegerField(verbose_name='절')),
                ('text', models.TextField(verbose_name='본문')),
            ],
            options={
                'verbose_name': '성경 구절',
                'verbose_name_plural': '성경 구절들',
                'db_table': 'bible_verses',
                'ordering': ['book__order', 'chapter', 'verse'],
            },
        ),
        migrations.CreateModel(
            name='BibleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='성경 번역본명')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='코드')),
                ('language', models.CharField(default='한국어', max_length=50, verbose_name='언어')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
            ],
            options={
                'verbose_name': '성경 번역본',
                'verbose_name_plural': '성경 번역본들',
                'db_table': 'bible_versions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='제목')),
                ('meditation', models.TextField(blank=True, verbose_name='묵상')),
                ('prayer', models.TextField(blank=True, verbose_name='기도문')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '일일 성경 구절',
                'verbose_name_plural': '일일 성경 구절들',
                'db_table': 'daily_verses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SermonScripture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='설교 제목')),
                ('preacher', models.CharField(max_length=100, verbose_name='설교자')),
                ('date', models.DateField(verbose_name='설교 날짜')),
                ('main_scripture', models.CharField(help_text='예: 요한복음 3:16', max_length=200, verbose_name='주 본문')),
                ('sub_scriptures', models.TextField(blank=True, help_text='여러 본문을 줄바꿈으로 구분', verbose_name='부 본문')),
                ('summary', models.TextField(blank=True, verbose_name='설교 요약')),
                ('outline', models.TextField(blank=True, verbose_name='설교 개요')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='sermons/audio/', verbose_name='음성 파일')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='sermons/video/', verbose_name='영상 파일')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='sermons/documents/', verbose_name='설교 원고')),
                ('service_type', models.CharField(default='주일예배', max_length=50, verbose_name='예배 종류')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '설교 본문',
                'verbose_name_plural': '설교 본문들',
                'db_table': 'sermon_scriptures',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BibleBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='제목')),
                ('note', models.TextField(blank=True, verbose_name='메모')),
                ('color', models.CharField(default='#ffff00', help_text='HEX 색상 코드', max_length=7, verbose_name='색상')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_bookmarks', to='church.church', verbose_name='교회')),
            ],
            options={
                'verbose_name': '성경 책갈피',
                'verbose_name_plural': '성경 책갈피들',
                'db_table': 'bible_bookmarks',
                'ordering': ['-created_at'],
            },
        ),
    ]
