# Generated by Django 5.2.1 on 2025-07-10 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bible', '0001_initial'),
        ('church', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblebookmark',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_bookmarks', to='members.member', verbose_name='교인'),
        ),
        migrations.AddField(
            model_name='biblestudy',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_studies', to='church.church', verbose_name='교회'),
        ),
    ]
