# Generated by Django 5.2.1 on 2025-07-10 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bible', '0002_initial'),
        ('church', '0001_initial'),
        ('groups', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='biblestudy',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bible_studies', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='biblestudy',
            name='end_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_ends', to='bible.biblebook', verbose_name='마지막 책'),
        ),
        migrations.AddField(
            model_name='biblestudy',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bible_studies', to='groups.group', verbose_name='대상 그룹'),
        ),
        migrations.AddField(
            model_name='biblestudy',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_bible_studies', to='members.member', verbose_name='인도자'),
        ),
        migrations.AddField(
            model_name='biblestudy',
            name='start_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_starts', to='bible.biblebook', verbose_name='시작 책'),
        ),
        migrations.AddField(
            model_name='bibleverse',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='bible.biblebook', verbose_name='책'),
        ),
        migrations.AddField(
            model_name='biblebookmark',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='bible.bibleverse', verbose_name='성경 구절'),
        ),
        migrations.AddField(
            model_name='bibleverse',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='bible.bibleversion', verbose_name='번역본'),
        ),
        migrations.AddField(
            model_name='dailyverse',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_verses', to='church.church', verbose_name='교회'),
        ),
        migrations.AddField(
            model_name='dailyverse',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_daily_verses', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='dailyverse',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_selections', to='bible.bibleverse', verbose_name='성경 구절'),
        ),
        migrations.AddField(
            model_name='sermonscripture',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermon_scriptures', to='church.church', verbose_name='교회'),
        ),
        migrations.AddField(
            model_name='sermonscripture',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sermons', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AlterUniqueTogether(
            name='biblebookmark',
            unique_together={('member', 'verse')},
        ),
        migrations.AddIndex(
            model_name='bibleverse',
            index=models.Index(fields=['book', 'chapter'], name='bible_verse_book_id_992204_idx'),
        ),
        migrations.AddIndex(
            model_name='bibleverse',
            index=models.Index(fields=['version', 'book', 'chapter'], name='bible_verse_version_8b5c4b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bibleverse',
            unique_together={('version', 'book', 'chapter', 'verse')},
        ),
        migrations.AlterUniqueTogether(
            name='dailyverse',
            unique_together={('church', 'date')},
        ),
        migrations.AddIndex(
            model_name='sermonscripture',
            index=models.Index(fields=['church', 'date'], name='sermon_scri_church__9c3492_idx'),
        ),
        migrations.AddIndex(
            model_name='sermonscripture',
            index=models.Index(fields=['preacher', 'date'], name='sermon_scri_preache_1ac3b0_idx'),
        ),
    ]
