# Generated by Django 5.2.1 on 2025-07-10 03:38

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(help_text='예: 김씨 가족, 이철수 가족', max_length=50, verbose_name='가족명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '가족 계보',
                'verbose_name_plural': '가족 계보들',
                'db_table': 'family_trees',
                'ordering': ['family_name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_code', models.CharField(help_text='교회별 고유 교인 번호', max_length=20, verbose_name='교인 번호')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('gender', models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성')], max_length=1, null=True, verbose_name='성별')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('lunar_birth', models.BooleanField(default=False, verbose_name='음력 생일')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='올바른 전화번호 형식이 아닙니다.', regex='^\\d{3}-\\d{3,4}-\\d{4}$')], verbose_name='휴대폰')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('address', models.TextField(blank=True, verbose_name='주소')),
                ('family_role', models.CharField(blank=True, help_text='세대주, 배우자, 자녀 등', max_length=20, verbose_name='가족 내 역할')),
                ('position', models.CharField(blank=True, help_text='목사, 전도사, 장로, 권사, 집사 등', max_length=50, verbose_name='직분')),
                ('baptism_date', models.DateField(blank=True, null=True, verbose_name='세례일')),
                ('confirmation_date', models.DateField(blank=True, null=True, verbose_name='입교일')),
                ('registration_date', models.DateField(default=datetime.date.today, verbose_name='등록일')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='members/profiles/', verbose_name='프로필 사진')),
                ('status', models.CharField(choices=[('active', '활동 교인'), ('inactive', '비활동 교인'), ('moved', '이전'), ('deceased', '소천')], default='active', max_length=20, verbose_name='상태')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('auto_group_enabled', models.BooleanField(default=True, verbose_name='자동 진급 대상')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '교인',
                'verbose_name_plural': '교인들',
                'db_table': 'members',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('spouse', '배우자'), ('parent', '부모'), ('child', '자녀'), ('sibling', '형제자매'), ('grandparent', '조부모'), ('grandchild', '손자녀'), ('uncle_aunt', '삼촌/이모/고모/외삼촌'), ('nephew_niece', '조카'), ('cousin', '사촌'), ('inlaw', '인척'), ('other', '기타')], max_length=20, verbose_name='관계')),
                ('relationship_detail', models.CharField(blank=True, help_text='예: 큰아들, 둘째딸, 시어머니 등', max_length=50, verbose_name='관계 상세')),
                ('is_confirmed', models.BooleanField(default=False, help_text='양방향 관계가 모두 설정되었는지 여부', verbose_name='확인됨')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_relationships', to='church.church', verbose_name='교회')),
            ],
            options={
                'verbose_name': '가족 관계',
                'verbose_name_plural': '가족 관계들',
                'db_table': 'family_relationships',
                'ordering': ['from_member__name', 'relationship'],
            },
        ),
    ]
