# Generated by Django 5.2.1 on 2025-07-10 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
        ('groups', '0002_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='familyrelationship',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_family_relationships', to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AddField(
            model_name='familytree',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_trees', to='church.church', verbose_name='교회'),
        ),
        migrations.AddField(
            model_name='familytree',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_family_trees', to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AddField(
            model_name='member',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='church.church', verbose_name='소속 교회'),
        ),
        migrations.AddField(
            model_name='member',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_members', to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AddField(
            model_name='member',
            name='groups',
            field=models.ManyToManyField(related_name='members', through='groups.GroupMember', to='groups.group', verbose_name='소속 그룹'),
        ),
        migrations.AddField(
            model_name='member',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_members', to='members.member', verbose_name='세대주'),
        ),
        migrations.AddField(
            model_name='familytree',
            name='family_members',
            field=models.ManyToManyField(related_name='family_trees', to='members.member', verbose_name='가족 구성원'),
        ),
        migrations.AddField(
            model_name='familytree',
            name='root_member',
            field=models.ForeignKey(help_text='가족의 대표가 되는 교인 (보통 세대주)', on_delete=django.db.models.deletion.CASCADE, related_name='rooted_family_trees', to='members.member', verbose_name='가족 대표'),
        ),
        migrations.AddField(
            model_name='familyrelationship',
            name='from_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_relations_from', to='members.member', verbose_name='기준 교인'),
        ),
        migrations.AddField(
            model_name='familyrelationship',
            name='to_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_relations_to', to='members.member', verbose_name='관계 교인'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['church', 'status'], name='members_church__312045_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['church', 'birth_date'], name='members_church__a0fd47_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['church', 'household'], name='members_church__bf3efc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('church', 'member_code')},
        ),
        migrations.AddIndex(
            model_name='familytree',
            index=models.Index(fields=['church', 'is_active'], name='family_tree_church__0810e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='familytree',
            unique_together={('church', 'family_name')},
        ),
        migrations.AddIndex(
            model_name='familyrelationship',
            index=models.Index(fields=['church', 'from_member'], name='family_rela_church__89e9d2_idx'),
        ),
        migrations.AddIndex(
            model_name='familyrelationship',
            index=models.Index(fields=['church', 'to_member'], name='family_rela_church__10c3e3_idx'),
        ),
        migrations.AddIndex(
            model_name='familyrelationship',
            index=models.Index(fields=['relationship'], name='family_rela_relatio_4660a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='familyrelationship',
            unique_together={('from_member', 'to_member', 'relationship')},
        ),
    ]
