# Generated by Django 5.2.1 on 2025-07-10 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='템플릿명')),
                ('worship_type', models.CharField(choices=[('sunday_morning', '주일 1부'), ('sunday_evening', '주일 2부'), ('wednesday', '수요예배'), ('friday', '금요철야'), ('dawn', '새벽예배'), ('special', '특별집회'), ('cell_group', '셀모임'), ('bible_study', '성경공부'), ('youth', '청년예배'), ('children', '어린이예배'), ('etc', '기타')], max_length=20, verbose_name='예배 종류')),
                ('day_of_week', models.IntegerField(choices=[(0, '월요일'), (1, '화요일'), (2, '수요일'), (3, '목요일'), (4, '금요일'), (5, '토요일'), (6, '일요일')], verbose_name='요일')),
                ('start_time', models.TimeField(verbose_name='시작 시간')),
                ('end_time', models.TimeField(verbose_name='종료 시간')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('auto_check_enabled', models.BooleanField(default=False, verbose_name='자동 출석 체크 활성화')),
                ('auto_check_time', models.TimeField(blank=True, null=True, verbose_name='자동 출석 체크 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '출석 템플릿',
                'verbose_name_plural': '출석 템플릿들',
                'db_table': 'attendance_templates',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('status', models.CharField(choices=[('present', '출석'), ('absent', '결석'), ('late', '지각'), ('early_leave', '조퇴'), ('excused', '공결'), ('sick', '병결')], default='present', max_length=20, verbose_name='출석 상태')),
                ('worship_type', models.CharField(choices=[('sunday_morning', '주일 1부'), ('sunday_evening', '주일 2부'), ('wednesday', '수요예배'), ('friday', '금요철야'), ('dawn', '새벽예배'), ('special', '특별집회'), ('cell_group', '셀모임'), ('bible_study', '성경공부'), ('youth', '청년예배'), ('children', '어린이예배'), ('etc', '기타')], max_length=20, verbose_name='예배 종류')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('arrival_time', models.TimeField(blank=True, null=True, verbose_name='도착 시간')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='출발 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='church.church', verbose_name='소속 교회')),
            ],
            options={
                'verbose_name': '출석',
                'verbose_name_plural': '출석들',
                'db_table': 'attendance',
                'ordering': ['-date', 'worship_type', 'member__name'],
            },
        ),
    ]
