# Generated by Django 5.1.3 on 2025-07-09 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('status', models.CharField(choices=[('PRESENT', '출석'), ('ABSENT', '결석'), ('LATE', '지각'), ('ETC', '기타')], max_length=10, verbose_name='상태')),
                ('worship_type', models.CharField(choices=[('SUNDAY', '주일예배'), ('WEDNESDAY', '수요예배'), ('FRIDAY', '금요철야'), ('DAWN', '새벽예배'), ('SPECIAL', '특별집회'), ('ETC', '기타')], max_length=20, verbose_name='예배 종류')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.church', verbose_name='소속 교회')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='교인')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='기록자')),
            ],
            options={
                'verbose_name': '출석',
                'verbose_name_plural': '출석',
                'unique_together': {('member', 'date', 'worship_type')},
            },
        ),
    ]
