# Generated by Django 5.2.1 on 2025-07-10 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0003_initial'),
        ('church', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL, verbose_name='기록자'),
        ),
        migrations.AddField(
            model_name='attendancetemplate',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_templates', to='church.church', verbose_name='소속 교회'),
        ),
        migrations.AddField(
            model_name='attendancetemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendance_templates', to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AddField(
            model_name='attendancetemplate',
            name='target_groups',
            field=models.ManyToManyField(blank=True, related_name='attendance_templates', to='groups.group', verbose_name='대상 그룹'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['church', 'date'], name='attendance_church__7aaccd_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['member', 'date'], name='attendance_member__106678_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['worship_type', 'date'], name='attendance_worship_2d0c24_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('member', 'date', 'worship_type')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancetemplate',
            unique_together={('church', 'name')},
        ),
    ]
